---
title: "Seasonal timeseries"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Seasonal timeseries}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(magrittr)
```

## Data

```{r}
d_day <- covidnor::total[
  granularity_geo=="county" & 
  granularity_time=="day",
  .(
    isoyear,
    date,
    location_code,
    location_name,
    cases_by_testdate_n,
    cases_by_testdate_vs_pop_pr100000
  )
] %>% 
  print()
d_isoweek <- covidnor::total[
  granularity_geo=="county" & 
  granularity_time=="isoweek",
  .(
    isoyear,
    isoyearweek,
    season,
    seasonweek,
    location_code,
    location_name,
    cases_by_testdate_n,
    cases_by_testdate_vs_pop_pr100000
  )
] %>% 
  print()
```

## Graphs for one geographical area

```{r}
csstyle::plot_seasonal_timeseries(
  d_isoweek[location_code %in% c("county_nor03")],
  x_var = "isoyearweek",
  x_breaks = seq(1,52, 4),
  x_lab = "Isoweek",
  y_var = "cases_by_testdate_vs_pop_pr100000",
  y_labels = csstyle::format_num_as_nor_per100k_0,
  lab_title = "COVID-19 cases per 100 000 population.",
  lab_subtitle = "Cases are recorded by date of positive PCR-test.",
  # breaks_x = csstyle::every_nth(8),
  #breaks_x = c(3, 6),
  wide_table = FALSE,
  var_group = "season"
)
```


