---
title: "Timeseries"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Timeseries}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(magrittr)
```

## Data

```{r}
d_day <- covidnor::total[
  granularity_geo=="county" & 
  granularity_time=="day",
  .(
    isoyear,
    date,
    location_code,
    location_name,
    cases_by_testdate_n,
    cases_by_testdate_vs_pop_pr100000
  )
] %>% 
  print()
d_isoweek <- covidnor::total[
  granularity_geo=="county" & 
  granularity_time=="isoweek",
  .(
    isoyear,
    isoyearweek,
    season,
    seasonweek,
    location_code,
    location_name,
    cases_by_testdate_n,
    cases_by_testdate_vs_pop_pr100000
  )
] %>% 
  print()
```

## Graphs for one geographical area

Daily epicurve for `county_nor03`

```{r}
csstyle::plot_timeseries(
  d_day[location_code=="county_nor03"],
  var_x = "date",
  var_y = c("Cases" = "cases_by_testdate_n"),
  breaks_x = "2 months"
)
```

Weekly epicurve for `county_nor03`

```{r}
csstyle::plot_timeseries(
  d_isoweek[location_code %in% c("county_nor03", "county_nor50")],
  var_x = "isoyearweek",
  var_y = "cases_by_testdate_vs_pop_pr100000",
  breaks_x = csstyle::every_nth(8),
  wide_table = FALSE,
  var_group = "location_name"
)
```
