---
title: "Timeseries"
author: "Celine Victoria Berg-Hansen"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Timeseries}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(ggplot2)
library(data.table)
library(splstyle)
```

## Data

We generally start with a linelist dataset (make sure it is a `data.table`!).

```{r}
d <- norway_covid19_cases_by_time_location

# There is a lot of data in this dataset, so we'll just use 2022 data here
d <- d[isoyear == 2021]

# We have one daily dataset
d_day <- d[granularity_time == "day"]

# We have one weekly dataset
d_week <- d[granularity_time == "isoweek"]
```

## Graph for one geographical area

Weekly timeseries for `norge`

```{r}
plot_timeseries(d_week[granularity_geo == "nation"], 
                var_y = c("Covid cases" = "covid19_cases_testdate_n"), 
                breaks_x = every_nth(4), 
                breaks_y = splstyle::pretty_breaks(5))
```

```{r}
plot_timeseries(d_week[granularity_geo == "county"], 
                var_y = c("Covid cases" = "covid19_cases_testdate_n"), 
                breaks_x = every_nth(4), 
                breaks_y = splstyle::pretty_breaks(5),
                var_group = "location_code")
```


## Epicurves for multiple geographical areas

When we have multiple geographical areas, we use the argument `facet_wrap` to create multiple epicurves.

Daily epicurve for all of the counties

```{r fig.height=10, fig.width=8}
plot_timeseries(d_week[granularity_geo == "county"],
              var_y = c("Covid cases" = "covid19_cases_testdate_n"), 
              lab_main = "Daily epicurve for all the counties",
              facet_wrap = "location_code",
              breaks_x = every_nth(10), 
              breaks_y = splstyle::pretty_breaks(5),
              lab_y = "Cases")
```


